# This file was generated by the docusign_rest:generate_config rake task.
# You can run 'rake docusign_rest:generate_config' as many times as you need
# to replace the content of this file with a new config.

require 'docusign_rest'

DocusignRest.configure do |config|
  config.username       = 'ak+11@businessinsighter.com'
  config.password       = 'NaynaBI1'
  config.integrator_key = '920f8820-b4b9-4453-9e44-d1b061ba96d4'
  config.account_id     = '1907319'
  #config.endpoint       = 'https://www.docusign.net/restapi'
  #config.api_version    = 'v1'
end

